#注意:
#1.yaml中的命名规范:规范名称应串案（“-”分隔），小写字母数字字符，必须以字母开头
#2.用两个空格表示结构，类似python语法.
server:
  port:8000

#指定当前环境.开发?测试?预发布?生产?
#还可以②jar包启动得时候在命令行中指定 -Dspring.profiles.active=dev ③.在IDE中指定
logging:
  level:
    root: info
  config: classpath:log4j2/log4j2-dev.xml


spring:
  cloud:
    gateway:
      routes:
      - id: p4_route
        uri: http://127.0.0.1:3521
        filters:
        #urlPath中去除S5
        - RewritePath=/s5/(?<segment>.*),/$\{segment}
        predicates:
        - Path=/s5/**
      - id: p5_route
        uri: lb://onecardAuthApi
#        uri: http://127.0.0.1:7424
        filters:
        predicates:
        - Path=/**
      httpclient:
        connect-timeout: 30
        pool:
          name: gatewayHttpClientPool

  redis:
    database: 0
    host: 10.5.1.2
    port: 6379
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    status:
      http-mapping: {'UP':200}


cutomer:
  dingdingAlertUrl: https://oapi.dingtalk.com/robot/send?access_token=1a826120faf0ebfc6fe2033abc842848adfa01c5573a22462a3c2e78e4f1176e
  #是否有报警
  alertSwith: false
  #用户接口
  user_url: http://47.94.43.203:9012

#自定义参数。通过http://127.0.0.1:8080/actuator/info获取
info:
  app:
    encoding: UTF-8
    
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #HostInfoEnvironmentPostProcessor这个类里构造方法获取ip
    appname: onecardAuthGateway
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       ## Eureka注册中心地址
       defaultZone: http://10.5.1.3:8765/eureka  
feign:
  hystrix:
    enabled: false  
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1   
  
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false
          isolation:
            thread:
              timeoutInMilliseconds: 3000  
